name: main pipeline

on:
  workflow_dispatch:

jobs:
  build: 
    uses: chitovas/.github/.github/workflows/build.yml@d68289a48bc236808f05658ca1b77bbf19b7e314
    with: 
      dotnet-version: '9.0'
  logging:
    runs-on: ubuntu-latest
    steps:
      - name: print 
        run: |
          echo "DIRECT VARIABLE: ${{ vars.ORG_CHITOVA_VARIABLE }} - $ORG_CHITOVA_VARIABLE"
          echo "STORED VARIABLE: ${{ env.ORG_CHITOVA_VARIABLE }} - $ORG_CHITOVA_VARIABLE"
          echo "STORED SECRET: ${{ env.SECRET }} ---  $SECRET"
         
  
