name: main pipeline

on:
  workflow_dispatch:

jobs:
  build: 
    uses: chitovas/.github/.github/workflows/build.yml@d68289a48bc236808f05658ca1b77bbf19b7e314
    with: 
      dotnet-version: '9.0'
  logging:
    runs-on: ubuntu-latest
    steps:
      - name: print 
        run: |
          echo "vars.ORG_CHITOVA_VARIABLE: ${{ vars.ORG_CHITOVA_VARIABLE }}"
          echo "$ORG_CHITOVA_VARIABLE"
          echo "vars.REPO_CHITOVA_VARIABLE: ${{ vars.REPO_CHITOVA_VARIABLE }}"
          echo "$REPO_CHITOVA_VARIABLE"
          echo "secrets.ORG_CHITOVA_SECRET: ${{ secrets.ORG_CHITOVA_SECRET }}"
          echo "$ORG_CHITOVA_SECRET"
          echo "vars.ENV_ENVIRONMENT: ${{ vars.ENV_ENVIRONMENT }}"
          echo "$ENV_ENVIRONMENT"
         
  
